// Generated by lsc from provenance.ts

datatype Option<T> = None | Some(value: T)

function StringTrimLeft(s: string): string
  ensures |StringTrimLeft(s)| <= |s|
  ensures StringTrimLeft(s) == "" || (|StringTrimLeft(s)| > 0 && StringTrimLeft(s)[0] != ' ')
  decreases |s|
{
  if |s| == 0 then ""
  else if s[0] == ' ' then StringTrimLeft(s[1..])
  else s
}

function StringTrimRight(s: string): string
  ensures |StringTrimRight(s)| <= |s|
  decreases |s|
{
  if |s| == 0 then ""
  else if s[|s|-1] == ' ' then StringTrimRight(s[..|s|-1])
  else s
}

function StringTrim(s: string): string
{
  StringTrimRight(StringTrimLeft(s))
}

datatype RawClaim = RawClaim(claim: string, evidenceKey: string, excerpt: string, sourceIds: Option<seq<string>>)

function isEmptyResult(result: string): bool
{
  if (result == "") then
    true
  else
    var trimmed := StringTrim(result);
    if (trimmed == "") then
      true
    else
      if ((((trimmed == "{}") || (trimmed == "[]")) || (trimmed == "null")) || (trimmed == "undefined")) then
        true
      else
        if ((trimmed == "{\"content\":[]}") || (trimmed == "{\"results\":[]}")) then
          true
        else
          false
}

lemma isEmptyResult_ensures(result: string)
  ensures ((result == "") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "{}") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "[]") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "null") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "undefined") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "{\"content\":[]}") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "{\"results\":[]}") ==> (isEmptyResult(result) == true))
{
}
