// Generated by lsc from provenance.ts

predicate IsJSWhitespace(c: char)
{
  c == '\U{0009}' || c == '\U{000A}' || c == '\U{000B}' || c == '\U{000C}' || c == '\U{000D}' ||
  c == '\U{0020}' || c == '\U{00A0}' || c == '\U{1680}' ||
  ('\U{2000}' <= c <= '\U{200A}') ||
  c == '\U{2028}' || c == '\U{2029}' || c == '\U{202F}' || c == '\U{205F}' ||
  c == '\U{3000}' || c == '\U{FEFF}'
}

function StringTrimLeft(s: string): string
  ensures |StringTrimLeft(s)| <= |s|
  ensures StringTrimLeft(s) == "" || (|StringTrimLeft(s)| > 0 && !IsJSWhitespace(StringTrimLeft(s)[0]))
  decreases |s|
{
  if |s| == 0 then ""
  else if IsJSWhitespace(s[0]) then StringTrimLeft(s[1..])
  else s
}

function StringTrimRight(s: string): string
  ensures |StringTrimRight(s)| <= |s|
  ensures StringTrimRight(s) == "" || (|StringTrimRight(s)| > 0 && !IsJSWhitespace(StringTrimRight(s)[|StringTrimRight(s)|-1]))
  decreases |s|
{
  if |s| == 0 then ""
  else if IsJSWhitespace(s[|s|-1]) then StringTrimRight(s[..|s|-1])
  else s
}

function StringTrim(s: string): string
{
  StringTrimRight(StringTrimLeft(s))
}

function isEmptyResult(result: string): bool
{
  ((result == "") || (var trimmed := StringTrim(result); ((trimmed == "") || (((((trimmed == "{}") || (trimmed == "[]")) || (trimmed == "null")) || (trimmed == "undefined")) || ((trimmed == "{\"content\":[]}") || (trimmed == "{\"results\":[]}"))))))
}

lemma isEmptyResult_ensures(result: string)
  ensures ((result == "") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "{}") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "[]") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "null") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "undefined") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "{\"content\":[]}") ==> (isEmptyResult(result) == true))
  ensures ((StringTrim(result) == "{\"results\":[]}") ==> (isEmptyResult(result) == true))
{
}
