// Generated by lsc from workflow.ts

method SetToSeq<T>(s: set<T>) returns (res: seq<T>)
  ensures forall x :: x in s <==> x in res
  ensures |res| == |s|
  ensures forall i, j :: 0 <= i < j < |res| ==> res[i] != res[j]
{
  var remaining := s;
  res := [];
  while remaining != {}
    invariant remaining <= s
    invariant forall x :: x in res <==> (x in s && x !in remaining)
    invariant |res| + |remaining| == |s|
    invariant forall i, j :: 0 <= i < j < |res| ==> res[i] != res[j]
    decreases remaining
  {
    var x :| x in remaining;
    res := res + [x];
    remaining := remaining - {x};
  }
}

datatype WorkflowNode = WorkflowNode(id: string, tool: string, args: map<string, int>)

// ── Proof helpers ──────────────────────────────────────────

ghost function NodeIds(nodes: seq<WorkflowNode>): set<string>
{
  set i | 0 <= i < |nodes| :: nodes[i].id
}

lemma NodeIdsBound(nodes: seq<WorkflowNode>)
  ensures |NodeIds(nodes)| <= |nodes|
{
  if |nodes| == 0 {
  } else {
    NodeIdsBound(nodes[..|nodes|-1]);
    assert NodeIds(nodes) <= NodeIds(nodes[..|nodes|-1]) + {nodes[|nodes|-1].id};
    SubsetCardinality(NodeIds(nodes), NodeIds(nodes[..|nodes|-1]) + {nodes[|nodes|-1].id});
  }
}

lemma SortedFullCoverage(
  nodes: seq<WorkflowNode>,
  nodeMap: map<string, WorkflowNode>,
  enqueued: set<string>,
  sortedLen: nat
)
  requires forall i, j :: 0 <= i < j < |nodes| ==> nodes[i].id != nodes[j].id
  requires nodeMap.Keys == NodeIds(nodes)
  requires NodeIds(nodes) <= enqueued
  requires enqueued <= nodeMap.Keys
  requires sortedLen == |enqueued|
  ensures sortedLen == |nodes|
{
  NodeIdsUnique(nodes);
  assert enqueued == nodeMap.Keys;
}

lemma NodeIdsUnique(nodes: seq<WorkflowNode>)
  requires forall i, j :: 0 <= i < j < |nodes| ==> nodes[i].id != nodes[j].id
  ensures |NodeIds(nodes)| == |nodes|
{
  if |nodes| == 0 {
  } else {
    var n := |nodes| - 1;
    var prefix := nodes[..n];
    var lastId := nodes[n].id;
    assert forall i, j :: 0 <= i < j < |prefix| ==> prefix[i].id != prefix[j].id;
    NodeIdsUnique(prefix);
    assert lastId !in NodeIds(prefix) by {
      forall x | x in NodeIds(prefix) ensures x != lastId {
        var k :| 0 <= k < |prefix| && prefix[k].id == x;
        assert nodes[k].id == x;
        assert k < n;
        assert nodes[k].id != nodes[n].id;
      }
    }
    assert NodeIds(nodes) == NodeIds(prefix) + {lastId} by {
      forall x | x in NodeIds(nodes) ensures x in NodeIds(prefix) + {lastId} {
        var k :| 0 <= k < |nodes| && nodes[k].id == x;
        if k < n { assert prefix[k].id == x; }
      }
      forall x | x in NodeIds(prefix) + {lastId} ensures x in NodeIds(nodes) {
        if x == lastId { assert nodes[n].id == x; }
        else { var k :| 0 <= k < |prefix| && prefix[k].id == x; assert nodes[k].id == x; }
      }
    }
  }
}

lemma SubsetCardinality(a: set<string>, b: set<string>)
  requires a <= b
  ensures |a| <= |b|
{
  if a == {} {
  } else {
    var x :| x in a;
    SubsetCardinality(a - {x}, b - {x});
  }
}

lemma SubsetEqualSize(a: set<string>, b: set<string>)
  requires a <= b
  requires |a| == |b|
  ensures a == b
{
  if b - a != {} {
    var x :| x in b - a;
    assert x in b;
    assert a <= b - {x};
    SubsetCardinality(a, b - {x});
    assert |b - {x}| == |b| - 1;
    assert |a| <= |b| - 1;
    assert false;
  }
  assert b - a == {};
  SetDiffEmpty(b, a);
}

lemma SetDiffEmpty(a: set<string>, b: set<string>)
  requires a - b == {}
  ensures a <= b
{
  forall x | x in a ensures x in b {
    if x !in b { assert x in a - b; }
  }
}

// ── Acyclicity ─────────────────────────────────────────────

ghost predicate IsRanking(nodeIds: set<string>, deps: map<string, set<string>>, rank: map<string, nat>)
{
  (forall v :: v in nodeIds ==> v in rank) &&
  forall k :: k in nodeIds && k in deps ==>
    forall v :: v in deps[k] && v in nodeIds ==> rank[v] < rank[k]
}

ghost predicate {:opaque} AdjacencyReverse(adjacency: map<string, seq<string>>, deps: map<string, set<string>>)
{
  forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in deps && k in deps[v]
}

ghost predicate {:opaque} AdjacencyDupFree(adjacency: map<string, seq<string>>)
{
  forall k :: k in adjacency ==> forall i, j :: 0 <= i < j < |adjacency[k]| ==> adjacency[k][i] != adjacency[k][j]
}

ghost predicate {:opaque} AdjAllInNodeMap(adjacency: map<string, seq<string>>, nodeMap: map<string, WorkflowNode>)
{
  forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
}

ghost predicate {:opaque} UnseenInv(remDeps: map<string, set<string>>, deps: map<string, set<string>>, seenIdNeighbors: set<string>, processed: set<string>)
{
  forall v :: v in remDeps && v in deps && v !in seenIdNeighbors ==> remDeps[v] == deps[v] - processed
}

ghost predicate {:opaque} SeenInv(remDeps: map<string, set<string>>, deps: map<string, set<string>>, seenIdNeighbors: set<string>, processed: set<string>, id: string)
{
  forall v :: v in remDeps && v in deps && v in seenIdNeighbors ==> remDeps[v] == deps[v] - processed - {id}
}

ghost predicate {:opaque} RemDepsValues(remDeps: map<string, set<string>>, deps: map<string, set<string>>)
{
  (forall k :: k in remDeps && k in deps ==> remDeps[k] <= deps[k])
  && (forall v :: v in remDeps && v !in deps ==> remDeps[v] == {})
}

ghost predicate {:opaque} RemDepsTracksProcessed(remDeps: map<string, set<string>>, deps: map<string, set<string>>, processed: set<string>)
{
  forall v :: v in remDeps && v in deps ==> remDeps[v] == deps[v] - processed
}

ghost predicate {:opaque} DepsReverseInAdj(nodes: seq<WorkflowNode>, deps: map<string, set<string>>, adjacency: map<string, seq<string>>)
{
  forall v :: v in NodeIds(nodes) && v in deps ==>
    forall d :: d in deps[v] && d in adjacency ==> v in adjacency[d]
}

ghost predicate {:opaque} NodeIdsNotInDepsEnqueued(nodes: seq<WorkflowNode>, deps: map<string, set<string>>, enqueued: set<string>)
{
  forall v :: v in NodeIds(nodes) && v !in deps ==> v in enqueued
}

ghost predicate {:opaque} NodeIdsEmptyRemDepsEnqueued(nodes: seq<WorkflowNode>, remDeps: map<string, set<string>>, enqueued: set<string>)
{
  forall v :: v in NodeIds(nodes) && v in remDeps && remDeps[v] == {} ==> v in enqueued
}

lemma UnseenSeenPreservation(
  remDeps_old: map<string, set<string>>,
  remDeps_new: map<string, set<string>>,
  deps: map<string, set<string>>,
  seenIdNeighbors_old: set<string>,
  neighbor: string,
  processed: set<string>,
  id: string
)
  requires UnseenInv(remDeps_old, deps, seenIdNeighbors_old, processed)
  requires SeenInv(remDeps_old, deps, seenIdNeighbors_old, processed, id)
  requires neighbor !in seenIdNeighbors_old
  requires neighbor in remDeps_old
  requires neighbor in deps
  requires id in remDeps_old[neighbor]
  requires remDeps_new == remDeps_old[neighbor := remDeps_old[neighbor] - {id}]
  ensures UnseenInv(remDeps_new, deps, seenIdNeighbors_old + {neighbor}, processed)
  ensures SeenInv(remDeps_new, deps, seenIdNeighbors_old + {neighbor}, processed, id)
{
  reveal UnseenInv();
  reveal SeenInv();
  forall v | v in remDeps_new && v in deps && v !in seenIdNeighbors_old + {neighbor}
    ensures remDeps_new[v] == deps[v] - processed {
  }
  forall v | v in remDeps_new && v in deps && v in seenIdNeighbors_old + {neighbor}
    ensures remDeps_new[v] == deps[v] - processed - {id} {
    if v == neighbor {
    } else {
    }
  }
}

lemma RemDepsValuesPreservation(
  remDeps_old: map<string, set<string>>,
  remDeps_new: map<string, set<string>>,
  deps: map<string, set<string>>,
  neighbor: string,
  id: string
)
  requires RemDepsValues(remDeps_old, deps)
  requires neighbor in remDeps_old
  requires neighbor in deps
  requires remDeps_new == remDeps_old[neighbor := remDeps_old[neighbor] - {id}]
  ensures RemDepsValues(remDeps_new, deps)
{
  reveal RemDepsValues();
}

lemma NodeIdsEmptyRemDepsEnqueuedPreservation(
  nodes: seq<WorkflowNode>,
  remDeps_old: map<string, set<string>>,
  remDeps_new: map<string, set<string>>,
  enqueued_old: set<string>,
  enqueued_new: set<string>,
  neighbor: string,
  id: string
)
  requires NodeIdsEmptyRemDepsEnqueued(nodes, remDeps_old, enqueued_old)
  requires neighbor in remDeps_old
  requires remDeps_new == remDeps_old[neighbor := remDeps_old[neighbor] - {id}]
  requires enqueued_old <= enqueued_new
  requires remDeps_new[neighbor] != {} || neighbor in enqueued_new
  ensures NodeIdsEmptyRemDepsEnqueued(nodes, remDeps_new, enqueued_new)
{
  reveal NodeIdsEmptyRemDepsEnqueued();
}

lemma RemDepsTracksProcessedAfterId(
  remDeps: map<string, set<string>>,
  deps: map<string, set<string>>,
  seenIdNeighbors: set<string>,
  old_processed: set<string>,
  id: string,
  adjacency: map<string, seq<string>>,
  nodes: seq<WorkflowNode>
)
  requires UnseenInv(remDeps, deps, seenIdNeighbors, old_processed)
  requires SeenInv(remDeps, deps, seenIdNeighbors, old_processed, id)
  requires DepsReverseInAdj(nodes, deps, adjacency)
  requires id in adjacency
  requires seenIdNeighbors == set ji | 0 <= ji < |adjacency[id]| :: adjacency[id][ji]
  requires forall v :: v in remDeps ==> v in NodeIds(nodes)
  ensures RemDepsTracksProcessed(remDeps, deps, old_processed + {id})
{
  reveal UnseenInv();
  reveal SeenInv();
  reveal RemDepsTracksProcessed();
  reveal DepsReverseInAdj();
  forall v | v in remDeps && v in deps ensures remDeps[v] == deps[v] - (old_processed + {id}) {
    if v in seenIdNeighbors {
    } else {
      assert v !in adjacency[id] by {
        forall ji | 0 <= ji < |adjacency[id]| ensures adjacency[id][ji] != v {
        }
      }
      assert id !in deps[v];
    }
  }
}

lemma AllNodesEnqueued(
  allNodes: set<string>,
  deps: map<string, set<string>>,
  enqueued: set<string>,
  rank: map<string, nat>
)
  requires IsRanking(allNodes, deps, rank)
  requires forall k :: k in allNodes && k in deps ==> deps[k] <= allNodes
  requires forall v :: v in allNodes && v !in deps ==> v in enqueued
  requires forall v :: v in allNodes && v in deps && deps[v] <= enqueued ==> v in enqueued
  ensures allNodes <= enqueued
{
  var remaining := allNodes - enqueued;
  if remaining == {} { SetDiffEmpty(allNodes, enqueued); return; }
  MinByRankExists(remaining, rank);
  var v :| v in remaining && forall u :: u in remaining ==> rank[v] <= rank[u];
  if v in deps {
    forall d | d in deps[v] ensures d in enqueued {
      assert d in allNodes;
      assert rank[d] < rank[v];
      assert d !in remaining;
    }
    assert deps[v] <= enqueued;
    assert v in enqueued;
  } else {
    assert v in enqueued;
  }
}

lemma MinByRankExists(s: set<string>, rank: map<string, nat>)
  requires s != {}
  requires forall v :: v in s ==> v in rank
  ensures exists r :: r in s && forall v :: v in s ==> rank[r] <= rank[v]
  decreases s
{
  var x :| x in s;
  if s == {x} {
  } else {
    var rest := s - {x};
    MinByRankExists(rest, rank);
    var m :| m in rest && forall v :: v in rest ==> rank[m] <= rank[v];
  }
}

// ── Main method ────────────────────────────────────────────

method topologicalSort(nodes: seq<WorkflowNode>, deps: map<string, set<string>>) returns (res: seq<WorkflowNode>)
  requires forall i, j :: 0 <= i < j < |nodes| ==> nodes[i].id != nodes[j].id
  requires forall k :: k in deps ==> k in NodeIds(nodes)
  requires forall k, v :: k in deps && v in deps[k] ==> v in NodeIds(nodes)
  requires exists rank: map<string, nat> :: IsRanking(NodeIds(nodes), deps, rank)
  ensures (|res| <= |nodes|)
  ensures |res| == |nodes|
{
  ghost var rank: map<string, nat> :| IsRanking(NodeIds(nodes), deps, rank);
  NodeIdsBound(nodes);
  var nodeMap: map<string, WorkflowNode> := map[];
  var i_n_idx := 0;
  while i_n_idx < |nodes|
    invariant (i_n_idx <= |nodes|)
    invariant forall ki: int :: ((ki >= 0) ==> (ki < i_n_idx) ==> (nodes[ki].id in nodeMap))
    invariant forall k :: k in nodeMap ==> k in NodeIds(nodes)
    invariant nodeMap.Keys <= NodeIds(nodes)
  {
    var n := nodes[i_n_idx];
    nodeMap := nodeMap[n.id := n];
    i_n_idx := i_n_idx + 1;
  }
  assert forall k :: k in NodeIds(nodes) ==> k in nodeMap;
  assert nodeMap.Keys == NodeIds(nodes);
  var inDegree: map<string, int> := map[];
  var adjacency: map<string, seq<string>> := map[];
  ghost var remDeps: map<string, set<string>> := map[];
  ghost var processed: set<string> := {};
  var i_node_idx := 0;
  while i_node_idx < |nodes|
    invariant (i_node_idx <= |nodes|)
    invariant inDegree.Keys <= nodeMap.Keys
    invariant adjacency.Keys <= nodeMap.Keys
    invariant remDeps.Keys <= nodeMap.Keys
    invariant remDeps.Keys == inDegree.Keys
    invariant forall k :: k in inDegree ==> inDegree[k] == |remDeps[k]|
    invariant forall k :: k in remDeps ==> remDeps[k] == {}
    invariant forall k :: k in adjacency ==> adjacency[k] == []
    invariant forall ki :: 0 <= ki < i_node_idx ==> nodes[ki].id in inDegree
    invariant forall ki :: 0 <= ki < i_node_idx ==> nodes[ki].id in adjacency
    invariant forall ki :: 0 <= ki < i_node_idx ==> nodes[ki].id in remDeps
  {
    var node := nodes[i_node_idx];
    assert node.id in nodeMap;
    inDegree := inDegree[node.id := 0];
    adjacency := adjacency[node.id := []];
    remDeps := remDeps[node.id := {}];
    i_node_idx := i_node_idx + 1;
  }
  assert forall k :: k in NodeIds(nodes) ==> k in inDegree;
  assert inDegree.Keys == nodeMap.Keys;
  assert adjacency.Keys == nodeMap.Keys;
  assert remDeps.Keys == nodeMap.Keys;
  var i_nodeId_keys := SetToSeq(deps.Keys);
  ghost var addedToAdjacency: set<string> := {};
  var i_nodeId_idx := 0;
  while i_nodeId_idx < |i_nodeId_keys|
    invariant (i_nodeId_idx <= |i_nodeId_keys|)
    invariant inDegree.Keys == nodeMap.Keys
    invariant adjacency.Keys == nodeMap.Keys
    invariant remDeps.Keys == nodeMap.Keys
    invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
    invariant forall k :: k in NodeIds(nodes) ==> k in inDegree && k in remDeps
    invariant forall ji :: 0 <= ji < i_nodeId_idx ==> i_nodeId_keys[ji] in remDeps && remDeps[i_nodeId_keys[ji]] == deps[i_nodeId_keys[ji]]
    invariant remDeps.Keys == inDegree.Keys
    invariant forall k :: k in remDeps ==> inDegree[k] == |remDeps[k]|
    invariant forall k :: k in NodeIds(nodes) && k !in deps ==> remDeps[k] == {}
    // adjacency is the reverse of deps (for processed entries)
    invariant forall ji :: 0 <= ji < i_nodeId_idx ==>
      forall d :: d in deps[i_nodeId_keys[ji]] && d in adjacency ==> i_nodeId_keys[ji] in adjacency[d]
    invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in deps && k in deps[v]
    invariant addedToAdjacency == set ji | 0 <= ji < i_nodeId_idx :: i_nodeId_keys[ji]
    invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in addedToAdjacency
    invariant forall k :: k in adjacency ==> forall i, j :: 0 <= i < j < |adjacency[k]| ==> adjacency[k][i] != adjacency[k][j]
  {
    var nodeId := i_nodeId_keys[i_nodeId_idx];
    assert nodeId in NodeIds(nodes);
    assert nodeId in nodeMap;
    assert nodeId !in addedToAdjacency by {
      forall ji | 0 <= ji < i_nodeId_idx ensures i_nodeId_keys[ji] != nodeId {
      }
    }
    var nodeDeps := deps[nodeId];
    inDegree := inDegree[nodeId := |nodeDeps|];
    remDeps := remDeps[nodeId := nodeDeps];
    var i_dep_seq := SetToSeq(nodeDeps);
    var i_dep_idx := 0;
    while i_dep_idx < |i_dep_seq|
      invariant (i_dep_idx <= |i_dep_seq|)
      invariant inDegree.Keys == nodeMap.Keys
      invariant adjacency.Keys == nodeMap.Keys
      invariant remDeps.Keys == nodeMap.Keys
      invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
      invariant forall ji :: 0 <= ji < i_nodeId_idx ==>
        forall d :: d in deps[i_nodeId_keys[ji]] && d in adjacency ==> i_nodeId_keys[ji] in adjacency[d]
      invariant forall j :: 0 <= j < i_dep_idx ==> (i_dep_seq[j] in adjacency ==> nodeId in adjacency[i_dep_seq[j]])
      invariant nodeId in deps
      invariant forall j :: 0 <= j < |i_dep_seq| ==> i_dep_seq[j] in deps[nodeId]
      invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in deps && k in deps[v]
      invariant addedToAdjacency == set ji | 0 <= ji < i_nodeId_idx :: i_nodeId_keys[ji]
      invariant nodeId !in addedToAdjacency
      invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in addedToAdjacency || v == nodeId
      invariant forall k :: k in adjacency && (forall j :: 0 <= j < i_dep_idx ==> i_dep_seq[j] != k) ==>
        forall v :: v in adjacency[k] ==> v in addedToAdjacency
      invariant forall k :: k in adjacency ==> forall i, j :: 0 <= i < j < |adjacency[k]| ==> adjacency[k][i] != adjacency[k][j]
    {
      var dep := i_dep_seq[i_dep_idx];
      assert forall j :: 0 <= j < i_dep_idx ==> i_dep_seq[j] != dep;
      if (dep in adjacency) {
        assert forall v :: v in adjacency[dep] ==> v in addedToAdjacency;
        assert nodeId !in adjacency[dep];
        adjacency := adjacency[dep := (adjacency[dep] + [nodeId])];
      }
      i_dep_idx := i_dep_idx + 1;
    }
    addedToAdjacency := addedToAdjacency + {nodeId};
    i_nodeId_idx := i_nodeId_idx + 1;
  }
  // Post Phase 2: adjacency is the complete reverse of deps
  assert forall v :: v in NodeIds(nodes) && v in deps ==>
    forall d :: d in deps[v] && d in adjacency ==> v in adjacency[d];
  ghost var enqueued: set<string> := {};
  var queue: seq<string> := [];
  var i_id_keys := SetToSeq(inDegree.Keys);
  var i_id_idx := 0;
  while i_id_idx < |i_id_keys|
    invariant (i_id_idx <= |i_id_keys|)
    invariant inDegree.Keys == nodeMap.Keys
    invariant adjacency.Keys == nodeMap.Keys
    invariant remDeps.Keys == nodeMap.Keys
    invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in deps && k in deps[v]
    invariant forall k :: k in adjacency ==> forall i, j :: 0 <= i < j < |adjacency[k]| ==> adjacency[k][i] != adjacency[k][j]
    invariant forall j :: 0 <= j < |queue| ==> queue[j] in nodeMap
    invariant forall k :: k in enqueued ==> k in inDegree && inDegree[k] <= 0
    invariant enqueued <= set j | 0 <= j < i_id_idx :: i_id_keys[j]
    invariant |queue| == |enqueued|
    invariant forall j :: 0 <= j < i_id_idx ==> (i_id_keys[j] in inDegree && inDegree[i_id_keys[j]] == 0 ==> i_id_keys[j] in enqueued)
  {
    var id := i_id_keys[i_id_idx];
    assert id !in (set j | 0 <= j < i_id_idx :: i_id_keys[j]);
    assert id !in enqueued;
    assert id in nodeMap;
    var degree := inDegree[id];
    if (degree == 0) {
      enqueued := enqueued + {id};
      queue := (queue + [id]);
    }
    i_id_idx := i_id_idx + 1;
  }
  assert forall k :: k in NodeIds(nodes) && k !in deps ==> k in enqueued;
  SubsetCardinality(enqueued, nodeMap.Keys);
  assert AdjacencyReverse(adjacency, deps) by { reveal AdjacencyReverse(); }
  assert AdjacencyDupFree(adjacency) by { reveal AdjacencyDupFree(); }
  assert AdjAllInNodeMap(adjacency, nodeMap) by { reveal AdjAllInNodeMap(); }
  assert RemDepsValues(remDeps, deps) by { reveal RemDepsValues(); }
  assert RemDepsTracksProcessed(remDeps, deps, processed) by { reveal RemDepsTracksProcessed(); }
  assert NodeIdsNotInDepsEnqueued(nodes, deps, enqueued) by { reveal NodeIdsNotInDepsEnqueued(); }
  assert NodeIdsEmptyRemDepsEnqueued(nodes, remDeps, enqueued) by { reveal NodeIdsEmptyRemDepsEnqueued(); }
  assert DepsReverseInAdj(nodes, deps, adjacency) by { reveal DepsReverseInAdj(); }
  var sorted: seq<WorkflowNode> := [];
  while (|queue| > 0)
    invariant inDegree.Keys == nodeMap.Keys
    invariant adjacency.Keys == nodeMap.Keys
    invariant AdjacencyReverse(adjacency, deps)
    invariant AdjacencyDupFree(adjacency)
    invariant forall j :: 0 <= j < |queue| ==> queue[j] in nodeMap
    invariant AdjAllInNodeMap(adjacency, nodeMap)
    invariant forall k :: k in enqueued ==> k in inDegree && inDegree[k] <= 0
    invariant enqueued <= nodeMap.Keys
    invariant |sorted| + |queue| == |enqueued|
    invariant |enqueued| <= |nodeMap|
    invariant NodeIdsNotInDepsEnqueued(nodes, deps, enqueued)
    invariant remDeps.Keys == nodeMap.Keys
    invariant |processed| == |sorted|
    invariant forall j :: 0 <= j < |queue| ==> queue[j] !in processed
    // Ghost: inDegree tracks remDeps size
    invariant forall k :: k in remDeps ==> k in inDegree && inDegree[k] == |remDeps[k]|
    invariant RemDepsValues(remDeps, deps)
    invariant NodeIdsEmptyRemDepsEnqueued(nodes, remDeps, enqueued)
    // Ghost: processed nodes are exactly enqueued minus queue
    invariant processed <= enqueued
    invariant DepsReverseInAdj(nodes, deps, adjacency)
    invariant RemDepsTracksProcessed(remDeps, deps, processed)
    decreases |nodeMap| - |sorted|
  {
    var id := queue[0];
    queue := queue[1..];
    sorted := (sorted + [nodeMap[id]]);
    var i_neighbor_idx := 0;
    ghost var seenIdNeighbors: set<string> := {};
    while i_neighbor_idx < |(if (id in adjacency) then (var i_value := adjacency[id]; i_value) else [])|
      invariant (i_neighbor_idx <= |(if (id in adjacency) then (var i_value := adjacency[id]; i_value) else [])|)
      invariant seenIdNeighbors == set ji | 0 <= ji < i_neighbor_idx :: adjacency[id][ji]
      invariant inDegree.Keys == nodeMap.Keys
      invariant adjacency.Keys == nodeMap.Keys
      invariant id in adjacency
      invariant id !in processed
      invariant AdjacencyReverse(adjacency, deps)
      invariant forall j :: 0 <= j < |queue| ==> queue[j] in nodeMap
      invariant AdjAllInNodeMap(adjacency, nodeMap)
      invariant forall k :: k in enqueued ==> k in inDegree && inDegree[k] <= 0
      invariant enqueued <= nodeMap.Keys
      invariant |sorted| + |queue| == |enqueued|
      invariant |enqueued| <= |nodeMap|
      invariant NodeIdsNotInDepsEnqueued(nodes, deps, enqueued)
      invariant remDeps.Keys == nodeMap.Keys
      invariant forall j :: 0 <= j < |queue| ==> queue[j] !in processed
      invariant forall k :: k in remDeps ==> k in inDegree && inDegree[k] == |remDeps[k]|
      invariant RemDepsValues(remDeps, deps)
      invariant AdjacencyDupFree(adjacency)
      invariant UnseenInv(remDeps, deps, seenIdNeighbors, processed)
      invariant SeenInv(remDeps, deps, seenIdNeighbors, processed, id)
      invariant processed <= enqueued
      invariant NodeIdsEmptyRemDepsEnqueued(nodes, remDeps, enqueued)
    {
      ghost var old_remDeps := remDeps;
      ghost var old_seenIdNeighbors := seenIdNeighbors;
      ghost var old_enqueued := enqueued;
      var neighbor := (if (id in adjacency) then (var i_value := adjacency[id]; i_value) else [])[i_neighbor_idx];
      assert neighbor == adjacency[id][i_neighbor_idx];
      assert neighbor in adjacency[id];
      assert neighbor in nodeMap by { reveal AdjAllInNodeMap(); }
      assert neighbor in deps && id in deps[neighbor] by { reveal AdjacencyReverse(); }
      assert neighbor in remDeps;
      assert neighbor !in seenIdNeighbors by {
        reveal AdjacencyDupFree();
        forall ji | 0 <= ji < i_neighbor_idx ensures adjacency[id][ji] != neighbor {
        }
      }
      assert remDeps[neighbor] == deps[neighbor] - processed by { reveal UnseenInv(); }
      assert id in remDeps[neighbor];
      var newDegree := ((if (neighbor in inDegree) then (var i_value := inDegree[neighbor]; i_value) else 0) - 1);
      assert newDegree == |remDeps[neighbor]| - 1;
      inDegree := inDegree[neighbor := newDegree];
      remDeps := remDeps[neighbor := (remDeps[neighbor] - {id})];
      assert inDegree[neighbor] == |remDeps[neighbor]|;
      if (newDegree == 0) {
        assert remDeps[neighbor] == {};
        assert neighbor !in enqueued;
        enqueued := enqueued + {neighbor};
        SubsetCardinality(enqueued, nodeMap.Keys);
        queue := (queue + [neighbor]);
      }
      seenIdNeighbors := seenIdNeighbors + {neighbor};
      i_neighbor_idx := i_neighbor_idx + 1;
      UnseenSeenPreservation(old_remDeps, remDeps, deps, old_seenIdNeighbors, neighbor, processed, id);
      assert UnseenInv(remDeps, deps, seenIdNeighbors, processed);
      assert SeenInv(remDeps, deps, seenIdNeighbors, processed, id);
      RemDepsValuesPreservation(old_remDeps, remDeps, deps, neighbor, id);
      assert RemDepsValues(remDeps, deps);
      NodeIdsEmptyRemDepsEnqueuedPreservation(nodes, old_remDeps, remDeps, old_enqueued, enqueued, neighbor, id);
      assert NodeIdsEmptyRemDepsEnqueued(nodes, remDeps, enqueued);
      assert NodeIdsNotInDepsEnqueued(nodes, deps, enqueued) by { reveal NodeIdsNotInDepsEnqueued(); }
    }
    // Re-establish outer invariant remDeps[v] == deps[v] - processed for the new processed.
    assert seenIdNeighbors == set ji | 0 <= ji < |adjacency[id]| :: adjacency[id][ji];
    assert forall v :: v in remDeps ==> v in NodeIds(nodes);
    ghost var old_processed := processed;
    processed := (processed + {id});
    RemDepsTracksProcessedAfterId(remDeps, deps, seenIdNeighbors, old_processed, id, adjacency, nodes);
    assert RemDepsTracksProcessed(remDeps, deps, processed);
    assert RemDepsValues(remDeps, deps) by { reveal RemDepsValues(); }
    assert NodeIdsNotInDepsEnqueued(nodes, deps, enqueued) by { reveal NodeIdsNotInDepsEnqueued(); }
    assert NodeIdsEmptyRemDepsEnqueued(nodes, remDeps, enqueued) by { reveal NodeIdsEmptyRemDepsEnqueued(); }
  }
  // Post loop: queue empty, so processed == enqueued
  // For any v with deps[v] <= enqueued: deps[v] <= processed, so remDeps[v] == deps[v] - processed == {}
  // So v in enqueued (by the remDeps == {} invariant)
  assert |queue| == 0;
  assert |processed| == |sorted| == |enqueued|;
  SubsetEqualSize(processed, enqueued);
  assert processed == enqueued;
  assert forall v :: v in NodeIds(nodes) && v in deps && deps[v] <= enqueued ==> v in enqueued by {
    reveal RemDepsTracksProcessed();
    reveal NodeIdsEmptyRemDepsEnqueued();
    forall v | v in NodeIds(nodes) && v in deps && deps[v] <= enqueued ensures v in enqueued {
      assert deps[v] <= processed;
      assert remDeps[v] == deps[v] - processed == {};
    }
  }
  assert forall v :: v in NodeIds(nodes) && v !in deps ==> v in enqueued by { reveal NodeIdsNotInDepsEnqueued(); }
  AllNodesEnqueued(NodeIds(nodes), deps, enqueued, rank);
  SortedFullCoverage(nodes, nodeMap, enqueued, |sorted|);
  if (|sorted| != |nodes|) {
    assert false;
  }
  return sorted;
}
