// Generated by lsc from workflow.ts

datatype Option<T> = None | Some(value: T)

method SetToSeq<T>(s: set<T>) returns (res: seq<T>)
  ensures forall x :: x in s <==> x in res
  ensures |res| == |s|
  ensures forall i, j :: 0 <= i < j < |res| ==> res[i] != res[j]
{
  var remaining := s;
  res := [];
  while remaining != {}
    invariant remaining <= s
    invariant forall x :: x in res <==> (x in s && x !in remaining)
    invariant |res| + |remaining| == |s|
    invariant forall i, j :: 0 <= i < j < |res| ==> res[i] != res[j]
    decreases remaining
  {
    var x :| x in remaining;
    res := res + [x];
    remaining := remaining - {x};
  }
}

datatype WorkflowNode = WorkflowNode(id: string, tool: string, args: map<string, int>)

// ── Proof helpers ──────────────────────────────────────────

ghost function NodeIds(nodes: seq<WorkflowNode>): set<string>
{
  set i | 0 <= i < |nodes| :: nodes[i].id
}

lemma NodeIdsBound(nodes: seq<WorkflowNode>)
  ensures |NodeIds(nodes)| <= |nodes|
{
  if |nodes| == 0 {
  } else {
    NodeIdsBound(nodes[..|nodes|-1]);
    assert NodeIds(nodes) <= NodeIds(nodes[..|nodes|-1]) + {nodes[|nodes|-1].id};
    SubsetCardinality(NodeIds(nodes), NodeIds(nodes[..|nodes|-1]) + {nodes[|nodes|-1].id});
  }
}

lemma SubsetCardinality(a: set<string>, b: set<string>)
  requires a <= b
  ensures |a| <= |b|
{
  if a == {} {
  } else {
    var x :| x in a;
    SubsetCardinality(a - {x}, b - {x});
  }
}

// ── Main method ────────────────────────────────────────────

method topologicalSort(nodes: seq<WorkflowNode>, deps: map<string, set<string>>) returns (res: seq<WorkflowNode>)
  requires forall k :: k in deps ==> k in NodeIds(nodes)
  requires forall k, v :: k in deps && v in deps[k] ==> v in NodeIds(nodes)
  ensures (|res| <= |nodes|)
{
  NodeIdsBound(nodes);
  var nodeMap := map[];
  var i_n_idx := 0;
  while i_n_idx < |nodes|
    invariant (i_n_idx <= |nodes|)
    invariant forall ki: int :: ((ki >= 0) ==> (ki < i_n_idx) ==> (nodes[ki].id in nodeMap))
    invariant forall k :: k in nodeMap ==> k in NodeIds(nodes)
    invariant nodeMap.Keys <= NodeIds(nodes)
  {
    var n := nodes[i_n_idx];
    nodeMap := nodeMap[n.id := n];
    i_n_idx := i_n_idx + 1;
  }
  assert forall k :: k in NodeIds(nodes) ==> k in nodeMap;
  assert nodeMap.Keys == NodeIds(nodes);
  var inDegree := map[];
  var adjacency := map[];
  var i_node_idx := 0;
  while i_node_idx < |nodes|
    invariant (i_node_idx <= |nodes|)
    invariant inDegree.Keys <= nodeMap.Keys
    invariant adjacency.Keys <= nodeMap.Keys
    invariant forall k :: k in adjacency ==> adjacency[k] == []
  {
    var node := nodes[i_node_idx];
    assert node.id in nodeMap;
    inDegree := inDegree[node.id := 0];
    adjacency := adjacency[node.id := []];
    i_node_idx := i_node_idx + 1;
  }
  var i_nodeId_keys := SetToSeq(deps.Keys);
  var i_nodeId_idx := 0;
  while i_nodeId_idx < |i_nodeId_keys|
    invariant (i_nodeId_idx <= |i_nodeId_keys|)
    invariant inDegree.Keys <= nodeMap.Keys
    invariant adjacency.Keys <= nodeMap.Keys
    invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
  {
    var nodeId := i_nodeId_keys[i_nodeId_idx];
    assert nodeId in NodeIds(nodes);
    assert nodeId in nodeMap;
    var nodeDeps := deps[nodeId];
    inDegree := inDegree[nodeId := |nodeDeps|];
    var i_dep_seq := SetToSeq(nodeDeps);
    var i_dep_idx := 0;
    while i_dep_idx < |i_dep_seq|
      invariant (i_dep_idx <= |i_dep_seq|)
      invariant adjacency.Keys <= nodeMap.Keys
      invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
    {
      var dep := i_dep_seq[i_dep_idx];
      if (dep in adjacency) {
        adjacency := adjacency[dep := (adjacency[dep] + [nodeId])];
      }
      i_dep_idx := i_dep_idx + 1;
    }
    i_nodeId_idx := i_nodeId_idx + 1;
  }
  ghost var enqueued: set<string> := {};
  var queue := [];
  var i_id_keys := SetToSeq(inDegree.Keys);
  var i_id_idx := 0;
  while i_id_idx < |i_id_keys|
    invariant (i_id_idx <= |i_id_keys|)
    invariant forall j :: 0 <= j < |queue| ==> queue[j] in nodeMap
    invariant forall k :: k in enqueued ==> k in inDegree && inDegree[k] <= 0
    invariant enqueued <= set j | 0 <= j < i_id_idx :: i_id_keys[j]
    invariant |queue| == |enqueued|
  {
    var id := i_id_keys[i_id_idx];
    assert id !in (set j | 0 <= j < i_id_idx :: i_id_keys[j]);
    assert id !in enqueued;
    assert id in nodeMap;
    var degree := inDegree[id];
    if (degree == 0) {
      enqueued := enqueued + {id};
      queue := (queue + [id]);
    }
    i_id_idx := i_id_idx + 1;
  }
  SubsetCardinality(enqueued, nodeMap.Keys);
  var sorted := [];
  while (|queue| > 0)
    invariant forall j :: 0 <= j < |queue| ==> queue[j] in nodeMap
    invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
    invariant forall k :: k in enqueued ==> k in inDegree && inDegree[k] <= 0
    invariant enqueued <= nodeMap.Keys
    invariant |sorted| + |queue| == |enqueued|
    invariant |enqueued| <= |nodeMap|
    decreases |nodeMap| - |sorted|
  {
    var id := queue[0];
    queue := queue[1..];
    sorted := (sorted + [nodeMap[id]]);
    var i_neighbor_idx := 0;
    var neighbors := if id in adjacency then adjacency[id] else [];
    while i_neighbor_idx < |(match (if id in adjacency then Some(adjacency[id]) else None) { case Some(i_value) => i_value case None => [] })|
      invariant (i_neighbor_idx <= |(match (if id in adjacency then Some(adjacency[id]) else None) { case Some(i_value) => i_value case None => [] })|)
      invariant 0 <= i_neighbor_idx <= |neighbors|
      invariant forall j :: 0 <= j < |queue| ==> queue[j] in nodeMap
      invariant forall k :: k in adjacency ==> forall v :: v in adjacency[k] ==> v in nodeMap
      invariant forall k :: k in enqueued ==> k in inDegree && inDegree[k] <= 0
      invariant enqueued <= nodeMap.Keys
      invariant |sorted| + |queue| == |enqueued|
      invariant |enqueued| <= |nodeMap|
    {
      var neighbor := (match (if id in adjacency then Some(adjacency[id]) else None) { case Some(i_value) => i_value case None => [] })[i_neighbor_idx];
      assert neighbor in nodeMap;
      var oldDeg := if neighbor in inDegree then inDegree[neighbor] else 0;
      var newDegree := ((match (if neighbor in inDegree then Some(inDegree[neighbor]) else None) { case Some(i_value) => i_value case None => 0 }) - 1);
      inDegree := inDegree[neighbor := newDegree];
      if (newDegree == 0) {
        assert neighbor !in enqueued;
        enqueued := enqueued + {neighbor};
        SubsetCardinality(enqueued, nodeMap.Keys);
        queue := (queue + [neighbor]);
      }
      i_neighbor_idx := i_neighbor_idx + 1;
    }
  }
  assert |sorted| + |queue| == |enqueued|;
  assert |queue| == 0;
  SubsetCardinality(enqueued, nodeMap.Keys);
  assert |sorted| <= |nodeMap|;
  assert nodeMap.Keys <= NodeIds(nodes);
  NodeIdsBound(nodes);
  if (|sorted| != |nodes|) {
    assert false;
  }
  return sorted;
}
