name: LemmaScript

on:
  push:
    branches: [lemma]
  pull_request:
    branches: [lemma]

jobs:
  verify:
    uses: midspiral/LemmaScript/.github/workflows/verify.yml@main
    with:
      backend: dafny
